### ISSUE TITLE
License violation?

### ISSUE THREAD

**Issue by frioux** [fglock/Perlito#42]
Only a big deal if you care, but it looks like this website is using perlito without including the Artistic License?  I'm def not a lawyer and can't remember what's required for users of AL2 but I thought you had to at least include the license.  Anyway check it out here: http://www.guru99.com/try-perl.html

**Comment by shlomif** [comment]
Hi @frioux! Thanks for your report. I noticed that people from guru99.com sent us E-mail spam to include their URLs here - http://hamakor.org.il/pipermail/websites/2016-March/000162.html - note that planet.linux.org.il is a webblog/web-feed aggregator and so we cannot change its content , so this E-mail may be automated.

As a result, I suggest we ignore the licence violation there, because contacting them will be risky.

**Comment by frioux** [comment]
You mean risky like they'll send you more email?

**Comment by fglock** [comment]
This doesn't seem to be a problem anymore, closing it for now.
